networks:
  testing_net:
    ipam:
      config:
      - subnet: 172.25.125.0/24
      driver: default
services:
  biz_scatter:
    container_name: biz_scatter
    depends_on:
    - citbiz_mapper0
    - citbiz_mapper1
    entrypoint: /scatter
    environment:
    - BIZSCA_BUSINESS_DATA=/data/test-business.json
    - BIZSCA_RABBITMQ_IP=rabbitmq
    - BIZSCA_RABBITMQ_PORT=5672
    - BIZSCA_CITBIZ_MAPPERS=2
    image: biz_scatter:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
    volumes:
    - business_dataset:/data
  citbiz_mapper0:
    container_name: citbiz_mapper0
    depends_on:
    - funcit_joiner0
    - funcit_joiner1
    entrypoint: /mapper
    environment:
    - CITBIZMAP_INSTANCE=0
    - CITBIZMAP_RABBITMQ_IP=rabbitmq
    - CITBIZMAP_RABBITMQ_PORT=5672
    - CITBIZMAP_BUSINESSES_INPUTS=1
    - CITBIZMAP_FUNCIT_JOINERS=2
    image: citbiz_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  citbiz_mapper1:
    container_name: citbiz_mapper1
    depends_on:
    - funcit_joiner0
    - funcit_joiner1
    entrypoint: /mapper
    environment:
    - CITBIZMAP_INSTANCE=1
    - CITBIZMAP_RABBITMQ_IP=rabbitmq
    - CITBIZMAP_RABBITMQ_PORT=5672
    - CITBIZMAP_BUSINESSES_INPUTS=1
    - CITBIZMAP_FUNCIT_JOINERS=2
    image: citbiz_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  funbiz_aggregator0:
    container_name: funbiz_aggregator0
    depends_on:
    - funcit_joiner0
    - funcit_joiner1
    entrypoint: /aggregator
    environment:
    - FUNBIZAGG_INSTANCE=0
    - FUNBIZAGG_RABBITMQ_IP=rabbitmq
    - FUNBIZAGG_RABBITMQ_PORT=5672
    - FUNBIZAGG_FUNBIZ_FILTERS=2
    - FUNBIZAGG_FUNCIT_JOINERS=2
    - FUNBIZAGG_INPUT_TOPIC=0
    image: funbiz_aggregator:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  funbiz_aggregator1:
    container_name: funbiz_aggregator1
    depends_on:
    - funcit_joiner0
    - funcit_joiner1
    entrypoint: /aggregator
    environment:
    - FUNBIZAGG_INSTANCE=1
    - FUNBIZAGG_RABBITMQ_IP=rabbitmq
    - FUNBIZAGG_RABBITMQ_PORT=5672
    - FUNBIZAGG_FUNBIZ_FILTERS=2
    - FUNBIZAGG_FUNCIT_JOINERS=2
    - FUNBIZAGG_INPUT_TOPIC=1
    image: funbiz_aggregator:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  funbiz_filter0:
    container_name: funbiz_filter0
    depends_on:
    - funbiz_aggregator0
    - funbiz_aggregator1
    entrypoint: /filter
    environment:
    - FUNBIZFIL_INSTANCE=0
    - FUNBIZFIL_RABBITMQ_IP=rabbitmq
    - FUNBIZFIL_RABBITMQ_PORT=5672
    - FUNBIZFIL_FUNBIZ_MAPPERS=2
    - FUNBIZFIL_FUNBIZ_AGGREGATORS=2
    image: funbiz_filter:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  funbiz_filter1:
    container_name: funbiz_filter1
    depends_on:
    - funbiz_aggregator0
    - funbiz_aggregator1
    entrypoint: /filter
    environment:
    - FUNBIZFIL_INSTANCE=1
    - FUNBIZFIL_RABBITMQ_IP=rabbitmq
    - FUNBIZFIL_RABBITMQ_PORT=5672
    - FUNBIZFIL_FUNBIZ_MAPPERS=2
    - FUNBIZFIL_FUNBIZ_AGGREGATORS=2
    image: funbiz_filter:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  funbiz_mapper0:
    container_name: funbiz_mapper0
    depends_on:
    - funbiz_filter0
    - funbiz_filter1
    entrypoint: /mapper
    environment:
    - FUNBIZMAP_INSTANCE=0
    - FUNBIZMAP_RABBITMQ_IP=rabbitmq
    - FUNBIZMAP_RABBITMQ_PORT=5672
    - FUNBIZMAP_REVIEWS_INPUTS=1
    - FUNBIZMAP_FUNBIZ_FILTERS=2
    image: funbiz_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  funbiz_mapper1:
    container_name: funbiz_mapper1
    depends_on:
    - funbiz_filter0
    - funbiz_filter1
    entrypoint: /mapper
    environment:
    - FUNBIZMAP_INSTANCE=1
    - FUNBIZMAP_RABBITMQ_IP=rabbitmq
    - FUNBIZMAP_RABBITMQ_PORT=5672
    - FUNBIZMAP_REVIEWS_INPUTS=1
    - FUNBIZMAP_FUNBIZ_FILTERS=2
    image: funbiz_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  funcit_aggregator0:
    container_name: funcit_aggregator0
    depends_on:
    - funcit_filter0
    - funcit_filter1
    entrypoint: /aggregator
    environment:
    - FUNCITAGG_INSTANCE=0
    - FUNCITAGG_RABBITMQ_IP=rabbitmq
    - FUNCITAGG_RABBITMQ_PORT=5672
    - FUNCITAGG_FUNCIT_JOINERS=2
    - FUNCITAGG_FUNCIT_FILTERS=2
    - FUNCITAGG_INPUT_TOPIC=0
    image: funcit_aggregator:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  funcit_aggregator1:
    container_name: funcit_aggregator1
    depends_on:
    - funcit_filter0
    - funcit_filter1
    entrypoint: /aggregator
    environment:
    - FUNCITAGG_INSTANCE=1
    - FUNCITAGG_RABBITMQ_IP=rabbitmq
    - FUNCITAGG_RABBITMQ_PORT=5672
    - FUNCITAGG_FUNCIT_JOINERS=2
    - FUNCITAGG_FUNCIT_FILTERS=2
    - FUNCITAGG_INPUT_TOPIC=1
    image: funcit_aggregator:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  funcit_filter0:
    container_name: funcit_filter0
    depends_on:
    - top_funniest_cities_prettier
    entrypoint: /filter
    environment:
    - FUNCITFIL_INSTANCE=0
    - FUNCITFIL_RABBITMQ_IP=rabbitmq
    - FUNCITFIL_RABBITMQ_PORT=5672
    - FUNCITFIL_FUNCIT_AGGREGATORS=2
    image: funcit_filter:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  funcit_filter1:
    container_name: funcit_filter1
    depends_on:
    - top_funniest_cities_prettier
    entrypoint: /filter
    environment:
    - FUNCITFIL_INSTANCE=1
    - FUNCITFIL_RABBITMQ_IP=rabbitmq
    - FUNCITFIL_RABBITMQ_PORT=5672
    - FUNCITFIL_FUNCIT_AGGREGATORS=2
    image: funcit_filter:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  funcit_joiner0:
    container_name: funcit_joiner0
    depends_on:
    - funcit_aggregator0
    - funcit_aggregator1
    entrypoint: /joiner
    environment:
    - FUNCITJOIN_INSTANCE=0
    - FUNCITJOIN_RABBITMQ_IP=rabbitmq
    - FUNCITJOIN_RABBITMQ_PORT=5672
    - FUNCITJOIN_FUNBIZ_AGGREGATORS=2
    - FUNCITJOIN_CITBIZ_MAPPERS=2
    - FUNCITJOIN_FUNCIT_AGGREGATORS=2
    - FUNCITJOIN_INPUT_TOPIC=0
    image: funcit_joiner:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  funcit_joiner1:
    container_name: funcit_joiner1
    depends_on:
    - funcit_aggregator0
    - funcit_aggregator1
    entrypoint: /joiner
    environment:
    - FUNCITJOIN_INSTANCE=1
    - FUNCITJOIN_RABBITMQ_IP=rabbitmq
    - FUNCITJOIN_RABBITMQ_PORT=5672
    - FUNCITJOIN_FUNBIZ_AGGREGATORS=2
    - FUNCITJOIN_CITBIZ_MAPPERS=2
    - FUNCITJOIN_FUNCIT_AGGREGATORS=2
    - FUNCITJOIN_INPUT_TOPIC=1
    image: funcit_joiner:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  mock_receiver0:
    container_name: mock_receiver0
    depends_on:
    - rabbitmq
    entrypoint: /receiver
    environment:
    - MOCK_TYPE=DIRECT
    - MOCK_RABBITMQ_IP=rabbitmq
    - MOCK_RABBITMQ_PORT=5672
    - MOCK_EXCHANGE=StarsAggregator
    - MOCK_TOPIC=0
    image: mock_receiver:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  mock_receiver1:
    container_name: mock_receiver1
    depends_on:
    - rabbitmq
    entrypoint: /receiver
    environment:
    - MOCK_TYPE=DIRECT
    - MOCK_RABBITMQ_IP=rabbitmq
    - MOCK_RABBITMQ_PORT=5672
    - MOCK_EXCHANGE=StarsAggregator
    - MOCK_TOPIC=1
    image: mock_receiver:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  rabbitmq:
    container_name: rabbitmq
    healthcheck:
      interval: 10s
      retries: '10'
      test: '["CMD", "curl", "-f", "http://rabbitmq:156722]'
      timeout: 5s
    image: rabbitmq:custom
    logging:
      driver: none
    networks:
    - testing_net
    ports:
    - 15672:15672
  rvw_scatter:
    container_name: rvw_scatter
    depends_on:
    - funbiz_mapper0
    - funbiz_mapper1
    - weekday_mapper0
    - weekday_mapper1
    - user_mapper0
    - user_mapper1
    - stars_mapper0
    - stars_mapper1
    entrypoint: /scatter
    environment:
    - RVWSCA_INSTANCE=0
    - RVWSCA_REVIEWS_DATA=/data/test-reviews.json
    - RVWSCA_RABBITMQ_IP=rabbitmq
    - RVWSCA_RABBITMQ_PORT=5672
    - RVWSCA_FUNBIZ_MAPPERS=2
    - RVWSCA_WEEKDAYS_MAPPERS=2
    - RVWSCA_HASHES_MAPPERS=1
    - RVWSCA_USERS_MAPPERS=2
    - RVWSCA_STARS_MAPPERS=2
    image: rvw_scatter:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
    volumes:
    - reviews_dataset:/data
  sink:
    container_name: sink
    depends_on:
    - mock_receiver0
    entrypoint: /sink
    environment:
    - SINK_RABBITMQ_IP=rabbitmq
    - SINK_RABBITMQ_PORT=5672
    image: sink:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  stars_aggregator0:
    container_name: stars_aggregator0
    depends_on:
    - sink
    entrypoint: /aggregator
    environment:
    - STARSAGG_INSTANCE=0
    - STARSAGG_RABBITMQ_IP=rabbitmq
    - STARSAGG_RABBITMQ_PORT=5672
    - STARSAGG_INPUT_TOPIC=0
    - STARSAGG_STARS_FILTERS=2
    - STARSAGG_STARS_JOINERS=2
    image: stars_aggregator:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  stars_aggregator1:
    container_name: stars_aggregator1
    depends_on:
    - sink
    entrypoint: /aggregator
    environment:
    - STARSAGG_INSTANCE=1
    - STARSAGG_RABBITMQ_IP=rabbitmq
    - STARSAGG_RABBITMQ_PORT=5672
    - STARSAGG_INPUT_TOPIC=1
    - STARSAGG_STARS_FILTERS=2
    - STARSAGG_STARS_JOINERS=2
    image: stars_aggregator:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  stars_filter0:
    container_name: stars_filter0
    depends_on:
    - stars_aggregator0
    - stars_aggregator1
    entrypoint: /filter
    environment:
    - STARSFIL_INSTANCE=0
    - STARSFIL_RABBITMQ_IP=rabbitmq
    - STARSFIL_RABBITMQ_PORT=5672
    - STARSFIL_STARS_MAPPERS=2
    - STARSFIL_STARS_AGGREGATORS=2
    image: stars_filter:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  stars_filter1:
    container_name: stars_filter1
    depends_on:
    - stars_aggregator0
    - stars_aggregator1
    entrypoint: /filter
    environment:
    - STARSFIL_INSTANCE=1
    - STARSFIL_RABBITMQ_IP=rabbitmq
    - STARSFIL_RABBITMQ_PORT=5672
    - STARSFIL_STARS_MAPPERS=2
    - STARSFIL_STARS_AGGREGATORS=2
    image: stars_filter:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  stars_mapper0:
    container_name: stars_mapper0
    depends_on:
    - stars_filter0
    - stars_filter1
    entrypoint: /mapper
    environment:
    - STARSMAP_INSTANCE=0
    - STARSMAP_RABBITMQ_IP=rabbitmq
    - STARSMAP_RABBITMQ_PORT=5672
    - STARSMAP_REVIEWS_INPUTS=1
    - STARSMAP_STARS_FILTERS=2
    image: stars_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  stars_mapper1:
    container_name: stars_mapper1
    depends_on:
    - stars_filter0
    - stars_filter1
    entrypoint: /mapper
    environment:
    - STARSMAP_INSTANCE=1
    - STARSMAP_RABBITMQ_IP=rabbitmq
    - STARSMAP_RABBITMQ_PORT=5672
    - STARSMAP_REVIEWS_INPUTS=1
    - STARSMAP_STARS_FILTERS=2
    image: stars_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  top_funniest_cities_prettier:
    container_name: top_funniest_cities_prettier
    depends_on:
    - sink
    entrypoint: /prettier
    environment:
    - FUNCITPRE_RABBITMQ_IP=rabbitmq
    - FUNCITPRE_RABBITMQ_PORT=5672
    - FUNCITPRE_FUNCIT_FILTERS=2
    image: top_funniest_cities_prettier:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  top_users_prettier:
    container_name: top_users_prettier
    depends_on:
    - sink
    entrypoint: /prettier
    environment:
    - TOPUSERPRE_RABBITMQ_IP=rabbitmq
    - TOPUSERPRE_RABBITMQ_PORT=5672
    - TOPUSERPRE_USER_FILTERS=2
    image: top_users_prettier:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  user_aggregator0:
    container_name: user_aggregator0
    depends_on:
    - user_filter0
    - user_filter1
    entrypoint: /aggregator
    environment:
    - USERAGG_INSTANCE=0
    - USERAGG_RABBITMQ_IP=rabbitmq
    - USERAGG_RABBITMQ_PORT=5672
    - USERAGG_INPUT_TOPIC=0
    - USERAGG_USER_MAPPERS=2
    - USERAGG_USER_FILTERS=2
    image: user_aggregator:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  user_aggregator1:
    container_name: user_aggregator1
    depends_on:
    - user_filter0
    - user_filter1
    entrypoint: /aggregator
    environment:
    - USERAGG_INSTANCE=1
    - USERAGG_RABBITMQ_IP=rabbitmq
    - USERAGG_RABBITMQ_PORT=5672
    - USERAGG_INPUT_TOPIC=1
    - USERAGG_USER_MAPPERS=2
    - USERAGG_USER_FILTERS=2
    image: user_aggregator:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  user_filter0:
    container_name: user_filter0
    depends_on:
    - top_users_prettier
    entrypoint: /filter
    environment:
    - USERFIL_INSTANCE=0
    - USERFIL_RABBITMQ_IP=rabbitmq
    - USERFIL_RABBITMQ_PORT=5672
    - USERFIL_USER_AGGREGATORS=2
    image: user_filter:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  user_filter1:
    container_name: user_filter1
    depends_on:
    - top_users_prettier
    entrypoint: /filter
    environment:
    - USERFIL_INSTANCE=1
    - USERFIL_RABBITMQ_IP=rabbitmq
    - USERFIL_RABBITMQ_PORT=5672
    - USERFIL_USER_AGGREGATORS=2
    image: user_filter:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  user_mapper0:
    container_name: user_mapper0
    depends_on:
    - user_aggregator0
    - user_aggregator1
    entrypoint: /mapper
    environment:
    - USERMAP_INSTANCE=0
    - USERMAP_RABBITMQ_IP=rabbitmq
    - USERMAP_RABBITMQ_PORT=5672
    - USERMAP_REVIEWS_INPUTS=1
    - USERMAP_USER_AGGREGATORS=2
    image: user_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  user_mapper1:
    container_name: user_mapper1
    depends_on:
    - user_aggregator0
    - user_aggregator1
    entrypoint: /mapper
    environment:
    - USERMAP_INSTANCE=1
    - USERMAP_RABBITMQ_IP=rabbitmq
    - USERMAP_RABBITMQ_PORT=5672
    - USERMAP_REVIEWS_INPUTS=1
    - USERMAP_USER_AGGREGATORS=2
    image: user_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  weekday_aggregator0:
    container_name: weekday_aggregator0
    depends_on:
    - weekday_histogram_prettier
    entrypoint: /aggregator
    environment:
    - WEEKDAYAGG_INSTANCE=0
    - WEEKDAYAGG_RABBITMQ_IP=rabbitmq
    - WEEKDAYAGG_RABBITMQ_PORT=5672
    - WEEKDAYAGG_INPUT_TOPIC=0
    - WEEKDAYAGG_WEEKDAY_MAPPERS=2
    image: weekday_aggregator:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  weekday_aggregator1:
    container_name: weekday_aggregator1
    depends_on:
    - weekday_histogram_prettier
    entrypoint: /aggregator
    environment:
    - WEEKDAYAGG_INSTANCE=1
    - WEEKDAYAGG_RABBITMQ_IP=rabbitmq
    - WEEKDAYAGG_RABBITMQ_PORT=5672
    - WEEKDAYAGG_INPUT_TOPIC=1
    - WEEKDAYAGG_WEEKDAY_MAPPERS=2
    image: weekday_aggregator:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  weekday_histogram_prettier:
    container_name: weekday_histogram_prettier
    depends_on:
    - sink
    entrypoint: /prettier
    environment:
    - HISTOPRE=0
    - HISTOPRE_RABBITMQ_IP=rabbitmq
    - HISTOPRE_RABBITMQ_PORT=5672
    - HISTOPRE_WEEKDAY_AGGREGATORS=2
    image: weekday_histogram_prettier:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  weekday_mapper0:
    container_name: weekday_mapper0
    depends_on:
    - weekday_aggregator0
    - weekday_aggregator1
    entrypoint: /mapper
    environment:
    - WEEKDAYMAP_INSTANCE=0
    - WEEKDAYMAP_RABBITMQ_IP=rabbitmq
    - WEEKDAYMAP_RABBITMQ_PORT=5672
    - WEEKDAYMAP_REVIEWS_INPUTS=1
    - WEEKDAYMAP_WEEKDAY_AGGREGATORS=2
    image: weekday_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  weekday_mapper1:
    container_name: weekday_mapper1
    depends_on:
    - weekday_aggregator0
    - weekday_aggregator1
    entrypoint: /mapper
    environment:
    - WEEKDAYMAP_INSTANCE=1
    - WEEKDAYMAP_RABBITMQ_IP=rabbitmq
    - WEEKDAYMAP_RABBITMQ_PORT=5672
    - WEEKDAYMAP_REVIEWS_INPUTS=1
    - WEEKDAYMAP_WEEKDAY_AGGREGATORS=2
    image: weekday_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
version: '3'
volumes:
  business_dataset:
    driver: local
    driver_opts:
      device: $PWD/datasets/business
      o: bind
      type: none
  reviews_dataset:
    driver: local
    driver_opts:
      device: $PWD/datasets/reviews
      o: bind
      type: none
