version: '3'

services:
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"

  rvw_scatter:
    container_name: rvw_scatter
    image: rvw_scatter:latest
    entrypoint: /scatter
    environment:
    - RVWSCA_CONFIG_FILE=/config/initial-config.yaml
    networks:
    - testing_net
    volumes:
    - reviews_dataset:/data
    - rvw_scatter_config_vol:/config

  rvw_receiver:
    container_name: rvw_receiver
    image: rvw_receiver:latest
    entrypoint: /receiver
    networks:
    - testing_net

volumes:
  reviews_dataset:
    driver: local
    driver_opts:
      device: $PWD/dataset/reviews
      o: bind
      type: none

  rvw_scatter_vol:
    driver: local
    driver_opts:
      device: $PWD/reviews-scatter/config
      o: bind
      type: none

networks:
  testing_net:
    ipam:
      config:
      - subnet: 172.25.125.0/24
      driver: default