version: '3'

services:
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:custom"
    ports:
      - "15672:15672"
    networks:
    - testing_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://rabbitmq:15672"]
      interval: 10s
      timeout: 5s
      retries: 10

  rvw_scatter:
    container_name: rvw_scatter
    image: rvw_scatter:latest
    entrypoint: /scatter
    restart: on-failure
    environment:
    - RVWSCA_CONFIG_FILE=/config/initial-config.yaml
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    networks:
    - testing_net
    volumes:
    - reviews_dataset:/data
    - rvw_scatter_vol:/config

  rvw_receiver:
    container_name: rvw_receiver
    image: rvw_receiver:latest
    entrypoint: /receiver
    restart: on-failure
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    networks:
    - testing_net

volumes:
  reviews_dataset:
    driver: local
    driver_opts:
      device: $PWD/datasets/reviews
      o: bind
      type: none

  business_dataset:
    driver: local
    driver_opts:
      device: $PWD/datasets/business
      o: bind
      type: none

  rvw_scatter_vol:
    driver: local
    driver_opts:
      device: $PWD/reviews-scatter/config
      o: bind
      type: none

networks:
  testing_net:
    ipam:
      config:
      - subnet: 172.25.125.0/24
      driver: default