networks:
  testing_net:
    ipam:
      config:
      - subnet: 172.25.125.0/24
      driver: default
services:
  funbiz_aggregator0:
    container_name: funbiz_aggregator0
    depends_on:
    - sink
    entrypoint: /aggregator
    environment:
    - FUNBIZAGG_RABBITMQ_IP=rabbitmq
    - FUNBIZAGG_RABBITMQ_PORT=5672
    - FUNBIZAGG_FUNBIZ_FILTERS=2
    - FUNBIZAGG_FUNBIZ_JOINERS=2
    - FUNBIZAGG_INPUT_TOPIC=0
    image: funbiz_aggregator:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  funbiz_aggregator1:
    container_name: funbiz_aggregator1
    depends_on:
    - sink
    entrypoint: /aggregator
    environment:
    - FUNBIZAGG_RABBITMQ_IP=rabbitmq
    - FUNBIZAGG_RABBITMQ_PORT=5672
    - FUNBIZAGG_FUNBIZ_FILTERS=2
    - FUNBIZAGG_FUNBIZ_JOINERS=2
    - FUNBIZAGG_INPUT_TOPIC=1
    image: funbiz_aggregator:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  funbiz_filter0:
    container_name: funbiz_filter0
    depends_on:
    - funbiz_aggregator0
    - funbiz_aggregator1
    entrypoint: /filter
    environment:
    - FUNBIZFIL_RABBITMQ_IP=rabbitmq
    - FUNBIZFIL_RABBITMQ_PORT=5672
    - FUNBIZFIL_FUNBIZ_MAPPERS=2
    - FUNBIZFIL_FUNBIZ_AGGREGATORS=2
    image: funbiz_filter:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  funbiz_filter1:
    container_name: funbiz_filter1
    depends_on:
    - funbiz_aggregator0
    - funbiz_aggregator1
    entrypoint: /filter
    environment:
    - FUNBIZFIL_RABBITMQ_IP=rabbitmq
    - FUNBIZFIL_RABBITMQ_PORT=5672
    - FUNBIZFIL_FUNBIZ_MAPPERS=2
    - FUNBIZFIL_FUNBIZ_AGGREGATORS=2
    image: funbiz_filter:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  funbiz_mapper0:
    container_name: funbiz_mapper0
    depends_on:
    - funbiz_filter0
    - funbiz_filter1
    entrypoint: /mapper
    environment:
    - FUNBIZMAP_RABBITMQ_IP=rabbitmq
    - FUNBIZMAP_RABBITMQ_PORT=5672
    - FUNBIZMAP_FUNBIZ_FILTERS=2
    image: funbiz_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  funbiz_mapper1:
    container_name: funbiz_mapper1
    depends_on:
    - funbiz_filter0
    - funbiz_filter1
    entrypoint: /mapper
    environment:
    - FUNBIZMAP_RABBITMQ_IP=rabbitmq
    - FUNBIZMAP_RABBITMQ_PORT=5672
    - FUNBIZMAP_FUNBIZ_FILTERS=2
    image: funbiz_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  histogram_mapper:
    container_name: histogram_mapper
    depends_on:
    - sink
    entrypoint: /mapper
    environment:
    - HISTOMAP_RABBITMQ_IP=rabbitmq
    - HISTOMAP_RABBITMQ_PORT=5672
    - HISTOMAP_WEEKDAY_AGGREGATORS=7
    image: histogram_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  mock_receiver0:
    container_name: mock_receiver0
    depends_on:
    - rabbitmq
    entrypoint: /receiver
    environment:
    - MOCK_TYPE=QUEUE
    - MOCK_RABBITMQ_IP=rabbitmq
    - MOCK_RABBITMQ_PORT=5672
    - MOCK_QUEUE=UserAggregator
    image: mock_receiver:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  rabbitmq:
    container_name: rabbitmq
    healthcheck:
      interval: 10s
      retries: '10'
      test: '["CMD", "curl", "-f", "http://rabbitmq:156722]'
      timeout: 5s
    image: rabbitmq:custom
    logging:
      driver: none
    networks:
    - testing_net
    ports:
    - 15672:15672
  rvw_scatter:
    container_name: rvw_scatter
    depends_on:
    - weekday_mapper0
    - weekday_mapper1
    - funbiz_mapper0
    - funbiz_mapper1
    - user_mapper0
    - user_mapper1
    entrypoint: /scatter
    environment:
    - RVWSCA_REVIEWS_DATA=/data/test-reviews.json
    - RVWSCA_RABBITMQ_IP=rabbitmq
    - RVWSCA_RABBITMQ_PORT=5672
    - RVWSCA_FUNBIZ_MAPPERS=2
    - RVWSCA_WEEKDAYS_MAPPERS=2
    - RVWSCA_HASHES_MAPPERS=1
    - RVWSCA_USERS_MAPPERS=2
    - RVWSCA_STARS_MAPPERS=1
    image: rvw_scatter:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
    volumes:
    - reviews_dataset:/data
  sink:
    container_name: sink
    depends_on:
    - mock_receiver0
    entrypoint: /sink
    environment:
    - SINK_RABBITMQ_IP=rabbitmq
    - SINK_RABBITMQ_PORT=5672
    image: sink:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  user_aggregator0:
    container_name: user_aggregator0
    depends_on:
    - histogram_mapper
    entrypoint: /aggregator
    environment:
    - USERAGG_RABBITMQ_IP=rabbitmq
    - USERAGG_RABBITMQ_PORT=5672
    - USERAGG_INPUT_TOPIC=0
    - USERAGG_USER_MAPPERS=2
    image: user_aggregator:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  user_aggregator1:
    container_name: user_aggregator1
    depends_on:
    - histogram_mapper
    entrypoint: /aggregator
    environment:
    - USERAGG_RABBITMQ_IP=rabbitmq
    - USERAGG_RABBITMQ_PORT=5672
    - USERAGG_INPUT_TOPIC=1
    - USERAGG_USER_MAPPERS=2
    image: user_aggregator:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  user_mapper0:
    container_name: user_mapper0
    depends_on:
    - sink
    - user_aggregator0
    - user_aggregator1
    entrypoint: /mapper
    environment:
    - USERMAP_RABBITMQ_IP=rabbitmq
    - USERMAP_RABBITMQ_PORT=5672
    - USERMAP_USER_AGGREGATORS=2
    image: user_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  user_mapper1:
    container_name: user_mapper1
    depends_on:
    - sink
    - user_aggregator0
    - user_aggregator1
    entrypoint: /mapper
    environment:
    - USERMAP_RABBITMQ_IP=rabbitmq
    - USERMAP_RABBITMQ_PORT=5672
    - USERMAP_USER_AGGREGATORS=2
    image: user_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  weekday_aggregator0:
    container_name: weekday_aggregator0
    depends_on:
    - histogram_mapper
    entrypoint: /aggregator
    environment:
    - WEEKDAYAGG_RABBITMQ_IP=rabbitmq
    - WEEKDAYAGG_RABBITMQ_PORT=5672
    - WEEKDAYAGG_INPUT_TOPIC=0
    - WEEKDAYAGG_WEEKDAY_MAPPERS=2
    image: weekday_aggregator:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  weekday_aggregator1:
    container_name: weekday_aggregator1
    depends_on:
    - histogram_mapper
    entrypoint: /aggregator
    environment:
    - WEEKDAYAGG_RABBITMQ_IP=rabbitmq
    - WEEKDAYAGG_RABBITMQ_PORT=5672
    - WEEKDAYAGG_INPUT_TOPIC=1
    - WEEKDAYAGG_WEEKDAY_MAPPERS=2
    image: weekday_aggregator:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  weekday_aggregator2:
    container_name: weekday_aggregator2
    depends_on:
    - histogram_mapper
    entrypoint: /aggregator
    environment:
    - WEEKDAYAGG_RABBITMQ_IP=rabbitmq
    - WEEKDAYAGG_RABBITMQ_PORT=5672
    - WEEKDAYAGG_INPUT_TOPIC=2
    - WEEKDAYAGG_WEEKDAY_MAPPERS=2
    image: weekday_aggregator:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  weekday_aggregator3:
    container_name: weekday_aggregator3
    depends_on:
    - histogram_mapper
    entrypoint: /aggregator
    environment:
    - WEEKDAYAGG_RABBITMQ_IP=rabbitmq
    - WEEKDAYAGG_RABBITMQ_PORT=5672
    - WEEKDAYAGG_INPUT_TOPIC=3
    - WEEKDAYAGG_WEEKDAY_MAPPERS=2
    image: weekday_aggregator:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  weekday_aggregator4:
    container_name: weekday_aggregator4
    depends_on:
    - histogram_mapper
    entrypoint: /aggregator
    environment:
    - WEEKDAYAGG_RABBITMQ_IP=rabbitmq
    - WEEKDAYAGG_RABBITMQ_PORT=5672
    - WEEKDAYAGG_INPUT_TOPIC=4
    - WEEKDAYAGG_WEEKDAY_MAPPERS=2
    image: weekday_aggregator:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  weekday_aggregator5:
    container_name: weekday_aggregator5
    depends_on:
    - histogram_mapper
    entrypoint: /aggregator
    environment:
    - WEEKDAYAGG_RABBITMQ_IP=rabbitmq
    - WEEKDAYAGG_RABBITMQ_PORT=5672
    - WEEKDAYAGG_INPUT_TOPIC=5
    - WEEKDAYAGG_WEEKDAY_MAPPERS=2
    image: weekday_aggregator:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  weekday_aggregator6:
    container_name: weekday_aggregator6
    depends_on:
    - histogram_mapper
    entrypoint: /aggregator
    environment:
    - WEEKDAYAGG_RABBITMQ_IP=rabbitmq
    - WEEKDAYAGG_RABBITMQ_PORT=5672
    - WEEKDAYAGG_INPUT_TOPIC=6
    - WEEKDAYAGG_WEEKDAY_MAPPERS=2
    image: weekday_aggregator:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  weekday_mapper0:
    container_name: weekday_mapper0
    depends_on:
    - weekday_aggregator0
    - weekday_aggregator1
    - weekday_aggregator2
    - weekday_aggregator3
    - weekday_aggregator4
    - weekday_aggregator5
    - weekday_aggregator6
    entrypoint: /mapper
    environment:
    - WEEKDAYMAP_RABBITMQ_IP=rabbitmq
    - WEEKDAYMAP_RABBITMQ_PORT=5672
    - WEEKDAYMAP_WEEKDAY_AGGREGATORS=7
    image: weekday_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  weekday_mapper1:
    container_name: weekday_mapper1
    depends_on:
    - weekday_aggregator0
    - weekday_aggregator1
    - weekday_aggregator2
    - weekday_aggregator3
    - weekday_aggregator4
    - weekday_aggregator5
    - weekday_aggregator6
    entrypoint: /mapper
    environment:
    - WEEKDAYMAP_RABBITMQ_IP=rabbitmq
    - WEEKDAYMAP_RABBITMQ_PORT=5672
    - WEEKDAYMAP_WEEKDAY_AGGREGATORS=7
    image: weekday_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
version: '3'
volumes:
  business_dataset:
    driver: local
    driver_opts:
      device: $PWD/datasets/business
      o: bind
      type: none
  reviews_dataset:
    driver: local
    driver_opts:
      device: $PWD/datasets/reviews
      o: bind
      type: none
