# Testing.
testing_mode: false
test_file_size: 1000

# System configuration.
reviews_streaming: false
reviews_pool_size: 16
business_pool_size: 16

# Bulks.
log_bulk_rate: 500
reviews_bulk_size: 1000
business_bulk_size: 1000
funbizagg_bulk_size: 1000
funcitjoin_bulk_size: 1000
funcitagg_bulk_size: 1000
hashagg_bulk_size: 1000
dishashagg_bulk_size: 1000
useragg_bulk_size: 1000
starsagg_bulk_size: 1000

# Logs
funniest_cities_logging: false
weekday_histogram_logging: false
best_users_logging: true
bot_users_logging: true
top_users_logging: true

# System specs.
users_min_reviews: 50
bots_min_reviews: 5
funniest_cities_top_size: 10

# Funniest cities flow.
citbiz_mappers: 1
funbiz_mappers: 1
funbiz_filters: 1
funbiz_aggregators: 1
funcit_joiners: 1
funcit_aggregators: 1
funcit_filters: 1

# Weekday histogram flow.
weekday_mappers: 1
weekday_aggregators: 1

# Users w/+50 reviews.
user_mappers: 1
user_aggregators: 1
user_filters: 1

# Users w/+50 5-stars reviews.
stars_mappers: 1
stars_filters: 1
stars_aggregators: 1
bestuser_joiners: 1

# Users w/+5 reviews with same text.
hash_mappers: 1
hash_aggregators: 1
dishash_aggregators: 1
dishash_filters: 1
botuser_filters: 1
botuser_joiners: 1
