# Testing
testing_mode: false
test_file_size: 1000

# System configuration:
reviews_streaming: false
reviews_bulk_size: 1750
reviews_pool_size: 20
business_bulk_size: 100
business_pool_size: 20
users_min_reviews: 50
bots_min_reviews: 5

# Funniest cities flow.
citbiz_mappers: 2
funbiz_mappers: 2
funbiz_filters: 2
funbiz_aggregators: 2
funcit_joiners: 2
funcit_aggregators: 2
funcit_filters: 2

# Weekday histogram flow.
weekday_mappers: 2
weekday_aggregators: 2

# Users w/+50 reviews.
user_mappers: 2
user_aggregators: 2
user_filters: 2

# Users w/+50 5-stars reviews.
stars_mappers: 2
stars_filters: 2
stars_aggregators: 2
bestuser_joiners: 2

# Users w/+5 reviews with same text.
hash_mappers: 2
hash_aggregators: 2
dishash_aggregators: 2
dishash_filters: 2
botuser_filters: 2
botuser_joiners: 2
