# Funniest cities flow.
funbiz_mappers: 2
funbiz_filters: 2
funbiz_aggregators: 2
funbiz_joiners: 2

# Weekday histogram flow.
weekday_mappers: 2
weekday_aggregators: 7

# Users w/+50 reviews.
user_mappers: 2
user_aggregators: 2
user_filters: 2

# Users w/+50 5-stars reviews.
stars_mappers: 1

# Users w/+5 reviews with same text.
hashes_mappers: 1
