#!/usr/bin/env python3

import sys
import yaml

input_yaml_file = open("./scripts/system-config.yaml")
input_yaml = yaml.load(input_yaml_file, Loader=yaml.FullLoader)

file = {}

#### VERSION
file['version'] = '3'

#### SERVICES
file['services'] = {}

# Services dependencies
# TODO: Change to ['rabbitmq']
SINK_DEPS = ['mock_receiver0']
HISTOPRE_DEPS = ['sink']
TOPUSERPRE_DEPS = ['sink']

FUNBIZAGG_DEPS = ['sink']
USERAGG_DEPS = []
WEEKDAYAGG_DEPS = []

FUNBIZFIL_DEPS = []
USERFIL_DEPS = []

USERMAP_DEPS = []
FUNBIZMAP_DEPS = []
WEEKDAYMAP_DEPS = []

BIZSCA_DEPS = ['sink']
RVWSCA_DEPS = []

file['services']['rabbitmq'] = {
	'container_name': f'rabbitmq',
	'image': 'rabbitmq:custom',
	'ports': ['15672:15672'],
	'networks': ['testing_net'],
	'logging': {
		'driver': 'none'
	},
	'healthcheck': {
		'test': '''["CMD", "curl", "-f", "http://rabbitmq:156722]''',
		'interval': '10s',
		'timeout': '5s',
		'retries': '10'
	}
}




# TODO: Remove mocks
file['services']['mock_receiver0'] = {
	'container_name': 'mock_receiver0',
	'image': 'mock_receiver:latest',
	'entrypoint': '/receiver',
	'restart': 'on-failure',
	'environment': ['MOCK_TYPE=QUEUE', 'MOCK_RABBITMQ_IP=rabbitmq', 'MOCK_RABBITMQ_PORT=5672', 'MOCK_QUEUE=BusinessScatter'],
	'links': ['rabbitmq'],
	'depends_on': ['rabbitmq'],
	'networks': ['testing_net']
}

#file['services']['mock_receiver0'] = {
#	'container_name': 'mock_receiver0',
#	'image': 'mock_receiver:latest',
#	'entrypoint': '/receiver',
#	'restart': 'on-failure',
#	'environment': ['MOCK_TYPE=DIRECT', 'MOCK_RABBITMQ_IP=rabbitmq', 'MOCK_RABBITMQ_PORT=5672', 'MOCK_EXCHANGE=UserMapper', 'MOCK_TOPIC=0'],
#	'links': ['rabbitmq'],
#	'depends_on': ['rabbitmq'],
#	'networks': ['testing_net']
#}
#
#file['services']['mock_receiver1'] = {
#	'container_name': 'mock_receiver1',
#	'image': 'mock_receiver:latest',
#	'entrypoint': '/receiver',
#	'restart': 'on-failure',
#	'environment': ['MOCK_TYPE=DIRECT', 'MOCK_RABBITMQ_IP=rabbitmq', 'MOCK_RABBITMQ_PORT=5672', 'MOCK_EXCHANGE=UserMapper', 'MOCK_TOPIC=1'],
#	'links': ['rabbitmq'],
#	'depends_on': ['rabbitmq'],
#	'networks': ['testing_net']
#}

















## Sink
file['services']['sink'] = {
	'container_name': 'sink',
	'image': 'sink:latest',
	'entrypoint': '/sink',
	'restart': 'on-failure',
	'environment': ['SINK_RABBITMQ_IP=rabbitmq', 'SINK_RABBITMQ_PORT=5672'],
	'links': ['rabbitmq'],
	'depends_on': list(SINK_DEPS),
	'networks': ['testing_net']
}

## Prettiers
WEEKDAYAGG_DEPS += ['weekday_histogram_prettier']
file['services']['weekday_histogram_prettier'] = {
	'container_name': 'weekday_histogram_prettier',
	'image': 'weekday_histogram_prettier:latest',
	'entrypoint': '/prettier',
	'restart': 'on-failure',
	'environment': ['HISTOPRE_RABBITMQ_IP=rabbitmq', 'HISTOPRE_RABBITMQ_PORT=5672', f'HISTOPRE_WEEKDAY_AGGREGATORS={input_yaml["weekday_aggregators"]}'],
	'links': ['rabbitmq'],
	'depends_on': list(HISTOPRE_DEPS),
	'networks': ['testing_net']
}

USERFIL_DEPS += ['top_users_prettier']
file['services']['top_users_prettier'] = {
	'container_name': 'top_users_prettier',
	'image': 'top_users_prettier:latest',
	'entrypoint': '/prettier',
	'restart': 'on-failure',
	'environment': ['TOPUSERPRE_RABBITMQ_IP=rabbitmq', 'TOPUSERPRE_RABBITMQ_PORT=5672', f'TOPUSERPRE_USER_FILTERS={input_yaml["user_filters"]}'],
	'links': ['rabbitmq'],
	'depends_on': list(TOPUSERPRE_DEPS),
	'networks': ['testing_net']
}

## Aggregators
for idx in range(0, input_yaml['funbiz_aggregators']):
	container_name = f'funbiz_aggregator{idx}'
	FUNBIZFIL_DEPS += [container_name]
	file['services'][container_name] = {
		'container_name': container_name,
		'image': 'funbiz_aggregator:latest',
		'entrypoint': '/aggregator',
		'restart': 'on-failure',
		'environment': ['FUNBIZAGG_RABBITMQ_IP=rabbitmq', 'FUNBIZAGG_RABBITMQ_PORT=5672', f'FUNBIZAGG_FUNBIZ_FILTERS={input_yaml["funbiz_filters"]}', f'FUNBIZAGG_FUNBIZ_JOINERS={input_yaml["funbiz_joiners"]}', f'FUNBIZAGG_INPUT_TOPIC={idx}'],
		'links': ['rabbitmq'],
		'depends_on': list(FUNBIZAGG_DEPS),
		'networks': ['testing_net']
	}

for idx in range(0, input_yaml['weekday_aggregators']):
	container_name = f'weekday_aggregator{idx}'
	WEEKDAYMAP_DEPS += [container_name]
	file['services'][container_name] = {
		'container_name': container_name,
		'image': 'weekday_aggregator:latest',
		'entrypoint': '/aggregator',
		'restart': 'on-failure',
		'environment': ['WEEKDAYAGG_RABBITMQ_IP=rabbitmq', 'WEEKDAYAGG_RABBITMQ_PORT=5672', f'WEEKDAYAGG_INPUT_TOPIC={idx}', f'WEEKDAYAGG_WEEKDAY_MAPPERS={input_yaml["weekday_mappers"]}'],
		'links': ['rabbitmq'],
		'depends_on': list(WEEKDAYAGG_DEPS),
		'networks': ['testing_net']
	}

for idx in range(0, input_yaml['user_aggregators']):
	container_name = f'user_aggregator{idx}'
	USERMAP_DEPS += [container_name]
	file['services'][container_name] = {
		'container_name': container_name,
		'image': 'user_aggregator:latest',
		'entrypoint': '/aggregator',
		'restart': 'on-failure',
		'environment': ['USERAGG_RABBITMQ_IP=rabbitmq', 'USERAGG_RABBITMQ_PORT=5672', f'USERAGG_INPUT_TOPIC={idx}', f'USERAGG_USER_MAPPERS={input_yaml["user_mappers"]}', f'USERAGG_USER_FILTERS={input_yaml["user_filters"]}'],
		'links': ['rabbitmq'],
		'depends_on': list(WEEKDAYAGG_DEPS),
		'networks': ['testing_net']
	}

## Filters
for idx in range(0, input_yaml['funbiz_filters']):
	container_name = f'funbiz_filter{idx}'
	FUNBIZMAP_DEPS += [container_name]
	file['services'][container_name] = {
		'container_name': container_name,
		'image': 'funbiz_filter:latest',
		'entrypoint': '/filter',
		'restart': 'on-failure',
		'environment': ['FUNBIZFIL_RABBITMQ_IP=rabbitmq', 'FUNBIZFIL_RABBITMQ_PORT=5672', f'FUNBIZFIL_FUNBIZ_MAPPERS={input_yaml["funbiz_mappers"]}', f'FUNBIZFIL_FUNBIZ_AGGREGATORS={input_yaml["funbiz_aggregators"]}'],
		'links': ['rabbitmq'],
		'depends_on': list(FUNBIZFIL_DEPS),
		'networks': ['testing_net']
	}

for idx in range(0, input_yaml['user_filters']):
	container_name = f'user_filter{idx}'
	USERAGG_DEPS += [container_name]
	file['services'][container_name] = {
		'container_name': container_name,
		'image': 'user_filter:latest',
		'entrypoint': '/filter',
		'restart': 'on-failure',
		'environment': ['USERFIL_RABBITMQ_IP=rabbitmq', 'USERFIL_RABBITMQ_PORT=5672', f'USERFIL_USER_AGGREGATORS={input_yaml["user_aggregators"]}'],
		'links': ['rabbitmq'],
		'depends_on': list(USERFIL_DEPS),
		'networks': ['testing_net']
	}

## Mappers
for idx in range(0, input_yaml['weekday_mappers']):
	container_name = f'weekday_mapper{idx}'
	RVWSCA_DEPS += [container_name]
	file['services'][container_name] = {
		'container_name': container_name,
		'image': 'weekday_mapper:latest',
		'entrypoint': '/mapper',
		'restart': 'on-failure',
		'environment': ['WEEKDAYMAP_RABBITMQ_IP=rabbitmq', 'WEEKDAYMAP_RABBITMQ_PORT=5672', f'WEEKDAYMAP_WEEKDAY_AGGREGATORS={input_yaml["weekday_aggregators"]}'],
		'links': ['rabbitmq'],
		'depends_on': list(WEEKDAYMAP_DEPS),
		'networks': ['testing_net']
	}

for idx in range(0, input_yaml['funbiz_mappers']):
	container_name = f'funbiz_mapper{idx}'
	RVWSCA_DEPS += [container_name]
	file['services'][container_name] = {
		'container_name': container_name,
		'image': 'funbiz_mapper:latest',
		'entrypoint': '/mapper',
		'restart': 'on-failure',
		'environment': ['FUNBIZMAP_RABBITMQ_IP=rabbitmq', 'FUNBIZMAP_RABBITMQ_PORT=5672', f'FUNBIZMAP_FUNBIZ_FILTERS={input_yaml["funbiz_filters"]}'],
		'links': ['rabbitmq'],
		'depends_on': list(FUNBIZMAP_DEPS),
		'networks': ['testing_net']
	}

for idx in range(0, input_yaml['user_mappers']):
	container_name = f'user_mapper{idx}'
	RVWSCA_DEPS += [container_name]
	file['services'][container_name] = {
		'container_name': container_name,
		'image': 'user_mapper:latest',
		'entrypoint': '/mapper',
		'restart': 'on-failure',
		'environment': ['USERMAP_RABBITMQ_IP=rabbitmq', 'USERMAP_RABBITMQ_PORT=5672', f'USERMAP_USER_AGGREGATORS={input_yaml["user_aggregators"]}'],
		'links': ['rabbitmq'],
		'depends_on': list(USERMAP_DEPS),
		'networks': ['testing_net']
	}

## Input Data
file['services']['rvw_scatter'] = {
	'container_name': 'rvw_scatter',
	'image': 'rvw_scatter:latest',
	'entrypoint': '/scatter',
	'restart': 'on-failure',
	'environment': ['RVWSCA_REVIEWS_DATA=/data/test-reviews.json', 'RVWSCA_RABBITMQ_IP=rabbitmq', 'RVWSCA_RABBITMQ_PORT=5672', f'RVWSCA_FUNBIZ_MAPPERS={input_yaml["funbiz_mappers"]}', f'RVWSCA_WEEKDAYS_MAPPERS={input_yaml["weekday_mappers"]}', f'RVWSCA_HASHES_MAPPERS={input_yaml["hashes_mappers"]}', f'RVWSCA_USERS_MAPPERS={input_yaml["user_mappers"]}', f'RVWSCA_STARS_MAPPERS={input_yaml["stars_mappers"]}'],
	'links': ['rabbitmq'],
	'depends_on': list(RVWSCA_DEPS),
	'networks': ['testing_net'],
	'volumes': ['reviews_dataset:/data']
}

file['services']['biz_scatter'] = {
	'container_name': 'biz_scatter',
	'image': 'biz_scatter:latest',
	'entrypoint': '/scatter',
	'restart': 'on-failure',
	'environment': ['BIZSCA_BUSINESS_DATA=/data/test-business.json', 'BIZSCA_RABBITMQ_IP=rabbitmq', 'BIZSCA_RABBITMQ_PORT=5672', f'BIZSCA_CITBIZ_MAPPERS={input_yaml["citbiz_mappers"]}'],
	'links': ['rabbitmq'],
	'depends_on': list(BIZSCA_DEPS),
	'networks': ['testing_net'],
	'volumes': ['business_dataset:/data']
}

#### VOLUMES
file['volumes'] = {
	'reviews_dataset': {
		'driver': 'local',
		'driver_opts': {
			'type': 'none',
			'device': '$PWD/datasets/reviews',
			'o': 'bind'
		}
	},
	'business_dataset': {
		'driver': 'local',
		'driver_opts': {
			'type': 'none',
			'device': '$PWD/datasets/business',
			'o': 'bind'
		}
	}
}

#### NETWORK
file['networks'] = {
	'testing_net': {
		'ipam': {
			'driver': 'default', 
			'config': [
				{'subnet': '172.25.125.0/24'}
			]
		}
	}
}

with open('docker-compose-dev.yaml', 'w') as outfile:
    yaml.dump(file, outfile, default_flow_style=False)
